framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
        
            #TODO: Se comento las siguientes lineas para no enviar los datos del correo
            #a una tabla en la base de datos.

            #Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            #Symfony\Component\Notifier\Message\ChatMessage: async
            #Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
